version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: db_internet_tv
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./csv:/var/lib/mysql-files
      - ./sql:/sql
    ports:
      - "3306:3306"
